/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Outcome of hitting a single endpoint once. */
export interface JsEndpointResult {
  name: string
  method: string
  path: string
  /** The configured `expect_status`, if the endpoint declared one. */
  expectedStatus?: number
  /** `0` when the request never reached the server (network error). */
  actualStatus: number
  latencyMs: number
  passed: boolean
  /** Response body (or network error) on failure; absent on success. */
  error?: string
}
/** Result of a `check` run: one entry per endpoint plus a summary count. */
export interface JsCheckResult {
  results: Array<JsEndpointResult>
  passed: number
  total: number
}
/** Hit every endpoint in the config once and report which passed. */
export declare function check(configPath: string): Promise<JsCheckResult>
/** Options for a fixed-rate load test. */
export interface JsRunOptions {
  configPath: string
  rps: number
  duration: number
}
/** Summary of a load test. */
export interface JsRunResult {
  totalRequests: number
  successRate: number
  p50: number
  p95: number
  p99: number
  p999: number
  durationSecs: number
}
/** Fire requests at a fixed rate for a fixed duration and report latency stats. */
export declare function run(options: JsRunOptions): Promise<JsRunResult>
/** Options for a seed run. */
export interface JsSeedOptions {
  configPath: string
  count: number
  concurrency: number
}
/** Summary of a seed run. */
export interface JsSeedResult {
  iterations: number
  passed: number
  totalRequests: number
}
/** Run the `seed`-tagged endpoints `count` times with bounded concurrency. */
export declare function seed(options: JsSeedOptions): Promise<JsSeedResult>
/** Options for a stress ramp. */
export interface JsStressOptions {
  configPath: string
  minRps: number
  maxRps: number
  step: number
  stepDuration: number
}
/** Result of a single RPS step in a stress ramp. */
export interface JsStressStep {
  rps: number
  requests: number
  successRate: number
  p50: number
  p95: number
  p99: number
  errors: number
  broke: boolean
}
/** Summary of a full stress ramp. */
export interface JsStressResult {
  steps: Array<JsStressStep>
  /** The RPS at which the API started failing, if a breaking point was hit. */
  breakingPoint?: number
}
/** Ramp RPS from `min_rps` to `max_rps`, stopping early at the breaking point. */
export declare function stress(options: JsStressOptions): Promise<JsStressResult>
