/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Smoke-test export: returns the Blast crate version.
 *
 * Exists so the NAPI build pipeline can be verified end-to-end before the
 * real bindings exist. Safe to remove once `check`/`run`/`seed`/`stress` land.
 */
export declare function version(): string
